### ISSUE TITLE
TypeError: compiler.plugin is not a function

### ISSUE THREAD

**Issue by seosmmbusiness** [elambro/laravel-mix-extract-media-queries#2]
Hi everyone.
I have an error 

`[webpack-cli] TypeError: compiler.plugin is not a function
    at MediaQuerySplittingPlugin.apply (/home/johnny/**/node_modules/@elambro/extract-css-media-queries/src/index.js:11:14)
    at createCompiler (/home/johnny/**/node_modules/webpack/lib/webpack.js:74:12)
    at create (/home/johnny/**/node_modules/webpack/lib/webpack.js:123:16)
    at webpack (/home/johnny/**/node_modules/webpack/lib/webpack.js:131:47)
    at WebpackCLI.f [as webpack] (/home/johnny/**/node_modules/webpack/lib/index.js:54:15)
    at WebpackCLI.createCompiler (/home/johnny/**/node_modules/webpack-cli/lib/webpack-cli.js:1845:29)
    at async WebpackCLI.buildCommand (/home/johnny/**/node_modules/webpack-cli/lib/webpack-cli.js:1952:20)
    at async Command.<anonymous> (/home/johnny/**/node_modules/webpack-cli/lib/webpack-cli.js:742:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/home/johnny/**/node_modules/webpack-cli/lib/webpack-cli.js:1289:13)`

It is caused by issues in new webpack plugin system.

Solved it by changing 
`compiler.plugin('emit', (compilation, callback) => {`

to 
 
`compiler.hooks.emit.tapAsync('emit', (compilation, callback) => {`

in src/index.js

I made a pull request but it was deleted. 
Hope you will update the repo.

**Comment by seosmmbusiness** [comment]
Sorry. Saw that it is changed already. =) 
Closing

**Comment by elambro** [comment]
> Sorry. Saw that it is changed already. =)
> Closing

Yep, I [merged it in last week](https://github.com/elambro/extract-css-media-queries/pull/3) on the webpack plugin. Thanks for that!
